---
- hosts: jenkins-slave
  become: yes
  tasks:
  - name: Update and upgrade yum packages
    yum: update_cache=yes
    when: ansible_os_family == "RedHat"

  - name: install JDK 11
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download & unarchive
    unarchive:
      src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.10/bin/apache-tomcat-10.0.10.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true

  - name: add lines to tomcat-users
    lineinfile: 
      dest: /opt/tomcat/conf/tomcat-users.xml
      insertbefore: '</tomcat-users>'
      line: '{{ item }}'
    with_items:
      - '<role rolename="tomcat"/>'
      - '<role rolename="manager-script"/>'
      - '<role rolename="manager-gui"/>'
      - '<role rolename="manager-jmx"/>'
      - '<role rolename="manager-status"/>'
      - '<role rolename="manager"/>'
      - '<user password="Reset123" roles="admin,admin-script,manager-gui,manager-script,manager-jmx,manager-status" username="tomcat"/>'

  - name: Comment  allow in meta-inf tomcat-users
    lineinfile: 
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml
      insertbefore: '<Context'
      line: '<!--'

  - name: Comment  allow in meta-inf tomcat-users
    lineinfile: 
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml
      insertbefore: '</Context>'
      line: '-->'

  #- name: permit traffic for jenkins port 8080/tcp
  #  firewalld:
  #    zone: public
  #    port: 8080/tcp
  #    permanent: yes
  #    immediate: yes
  #    state: enabled
