---
- name: Install Jenkins
  hosts: jenkins-master
  gather_facts: false
  become: true
  tasks:
  - import_role:
      name: jenkins

  - name: install JDK 11
    yum:
      name: ['java-1.8.0-openjdk-devel', 'git']
      state: present


