---
- name: Install Jenkins
  hosts: jenkins-master
  gather_facts: false
  become: true
  tasks:
  - import_role:
      name: jenkins

  - name: install git
    yum:
      name: ['git']
      state: present


