---

- name: Jenkins slave play
  hosts: jenkins-slave
  tasks:
  - name: install wget
    yum:
      name: wget
      state: present

  - name: install epel-release
    yum:
      name: epel-release
      state: present

  - name: install openjdk
    yum:
      name: java-1.8.0-openjdk
      state: present

  - name: create project directory
    file:
      path: "{{ path_list }}"
      state: directory
      mode: 0755
      owner: centos
      group: centos

- name: Jenkins Master play
  hosts: jenkins-master
  tasks:

  - name: Add Slave to Jenkins 
    jenkins_script:
     script: |
      import hudson.model.*
      import jenkins.model.*
      import hudson.slaves.*
      import hudson.slaves.EnvironmentVariablesNodeProperty.Entry
          
      import hudson.plugins.sshslaves.verifiers.*
          
      // Pick one of the strategies from the comments below this line
      SshHostKeyVerificationStrategy hostKeyVerificationStrategy = new NonVerifyingKeyVerificationStrategy()
          
      // Define a "Launch method": "Launch agents via SSH"
      ComputerLauncher launcher = new hudson.plugins.sshslaves.SSHLauncher(
              "${Host_id}", // Host
              22, // Port
              "${Credentials}", // Credentials
              (String)null, // JVM Options
              (String)null, // JavaPath
              (String)null, // Prefix Start Agent Command
              (String)null, // Suffix Start Agent Command
              (Integer)null, // Connection Timeout in Seconds
              (Integer)null, // Maximum Number of Retries
              (Integer)null, // The number of seconds to wait between retries
              hostKeyVerificationStrategy // Host Key Verification Strategy
      )
          
      // Define a "Permanent Agent"
      Slave agent = new DumbSlave(
              "${slave_name}",
              "${path01}",
              launcher)
      agent.nodeDescription = "Agent node description"
      agent.numExecutors = "${executors}"
      agent.labelString = "${label01}"
      agent.mode = Node.Mode.NORMAL
      agent.retentionStrategy = new RetentionStrategy.Always()
          
      List<Entry> env = new ArrayList<Entry>();
      env.add(new Entry("key1","value1"))
      env.add(new Entry("key2","value2"))
      EnvironmentVariablesNodeProperty envPro = new EnvironmentVariablesNodeProperty(env);
          
      agent.getNodeProperties().add(envPro)
          
      // Create a "Permanent Agent"
      Jenkins.instance.addNode(agent)
          
      return "Node has been created successfully."
     args:
       Host_id: "{{ Hostid }}"
       Credentials: "{{ Cred_Id }}"
       slave_name: "{{ slavename }}"
       path01: "{{ path_list }}"
       executors: "{{ execu }}"
       label01: "{{ label_01 }}"
     user: "{{ jen_usr }}"
     password: "{{ jen_pwd }}"
     validate_certs: no