- name: install plugin
  jenkins_plugin:
   name: "{{ item }}"
   state: latest
   url_username: admin
   url_password: "{{ adminpwd.stdout }}"
  with_items: "{{ jenkins_plugins }}"
  register: plugin_output

- name: Initiate the fact
  set_fact:
    jenkins_restart_required: no

- name: Check if restart is required by any of the plugins
  set_fact:
    jenkins_restart_required: yes
  when: item.changed
  with_items: "{{ plugin_output.results }}"

- name: Restart Jenkins if required
  service:
    name: jenkins
    state: restarted
  when: jenkins_restart_required